### PR TITLE
update cosyvoice code,add check ttsfrd

### PR DESCRIPTION
**Pull request by SpenserCai**
Update cosyvoice to newest version,and add check ttsfrd model (if have been installed ttsfrd,will download model auto)

### CODE REVIEW

**Comment by SpenserCai** [comment]
@AIFSH This update synchronizes the latest updates from CosyVoice

**Comment by melMass** [comment]
Nice was this tested on windows? In my fork I couldn't get either ttsfrd or WeTextProcessing to work

**Comment by SpenserCai** [comment]
> Nice was this tested on windows? In my fork I couldn't get either ttsfrd or WeTextProcessing to work

I currently do not have a Windows environment. After communicating with AIFSH, I will create a new repo, integrate relevant functions, and try to keep it updated as much as possible.

**Comment by SpenserCai** [comment]
The relevant content has been implemented by creating a new [repo](https://github.com/SpenserCai/ComfyUI-FunAudioLLM), this PR is closed.

**Pull request closed without merging**
